"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {formatJalali,toPersianDigits} from "@/lib/format";
type Cohort={id:string;title:string;starts_at:string;ends_at:string;policy_version:string};
type Member={userId:string;label:string};
type Row={id:number;cohortId:string;externalId:string;source:string;status:string;note:string|null;contact:string};
type Grant={grantRef:string;userId:string;cohortId:string;startsAt:string;endsAtExclusive:string;revokedAt:string|null};
type State={cohorts:Cohort[];members:Member[];registrations:Row[];grants:Grant[]};
export default function CourseOperations({transport=fetch}:{transport?:typeof fetch}={}){
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [cohort,setCohort]=useState(""),[target,setTarget]=useState(""),[csv,setCsv]=useState(""),[reason,setReason]=useState(""),[ref,setRef]=useState("");
 const [preview,setPreview]=useState<{importId:number;hash:string;total:number;rows:{externalId:string;status:string;contact:string}[]}|null>(null);
 const commandKeys=useRef(new Map<string,string>());
 const read=useCallback(async()=>{try{const r=await transport("/api/admin/course-operations",{cache:"no-store"});if(!r.ok)throw Error("گزارش دریافت نشد؛ دسترسی و نصب هستهٔ دوره بررسی شود.");const b=await r.json();setData(b.data);}catch(e){setError(e instanceof Error?e.message:"دریافت انجام نشد.");}},[transport]);
 useEffect(()=>{void read();},[read]);
 async function send(path:string,body:unknown){setBusy(true);setError("");setMessage("");try{if(path.includes("cohort-access") || ["create-cohort","cancel-cohort"].includes(String((body as {action?:string}).action))) {const request={...body as Record<string,unknown>};delete request.idempotencyKey;const signature=JSON.stringify(request);if(!commandKeys.current.has(signature))commandKeys.current.set(signature,crypto.randomUUID());body={...request,idempotencyKey:commandKeys.current.get(signature)};}const r=await transport(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw Error(b.error??"ذخیره انجام نشد.");setMessage("اقدام ثبت شد.");await read();return b;}catch(e){setError(e instanceof Error?e.message:"خطای شبکه؛ ورودی شما حفظ شده است.");return null;}finally{setBusy(false);}}
 const chosen=data?.cohorts.find(x=>x.id===cohort);
 return <div className="space-y-6" dir="rtl"><header><h1 className="text-2xl font-bold">عملیات دوره و ثبت‌نام</h1><p className="mt-2 text-muted">پیش‌نمایش، بررسی هویت و مجوز دلیل‌دار. ثبت‌نام تجاری و پرداخت فعال نیست.</p></header>
 {error&&<p role="alert" className="card p-4">{error}<button className="btn btn-secondary ms-3" onClick={()=>void read()}>تلاش دوباره</button></p>}{message&&<p role="status">{message}</p>}
 <section className="card p-5"><h2 className="font-bold mb-4">ایجاد پیش‌نویس دوره با سیاست صریح</h2><form className="grid gap-3 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await send("/api/admin/course-operations",{action:"create-cohort",title:f.get("title"),startsLocal:f.get("start"),calendar:f.get("calendar"),amount:Number(f.get("amount")),policyVersion:f.get("policy")});}}>
 <label>عنوان<input className="input w-full" name="title" minLength={3} required/></label><label>شروع به وقت تهران<input className="input w-full" type="datetime-local" name="start" required/></label>
 <label>قاعدهٔ پیشنهادی<select className="input w-full" name="calendar"><option value="gregorian-calendar-months">ماه تقویمی میلادی</option><option value="fixed-days">تعداد روز</option></select></label><label>تعداد<input className="input w-full" type="number" name="amount" min={1} max={366} required/></label>
 <label>نام نسخهٔ سیاست<input className="input w-full" name="policy" minLength={3} placeholder="نسخهٔ آزمایشی انتخاب‌شده" required/></label><button className="btn btn-primary" disabled={busy}>ذخیرهٔ پیش‌نویس</button></form></section>
 <section className="card p-5 space-y-3"><h2 className="font-bold">واردسازی کنترل‌شدهٔ CSV</h2><label className="block">دوره<select className="input w-full" value={cohort} onChange={e=>{setCohort(e.target.value);setPreview(null);}}><option value="">انتخاب دوره</option>{data?.cohorts.map(c=><option key={c.id} value={c.id}>{c.title} · {formatJalali(c.starts_at)}</option>)}</select></label>
 {chosen&&<p>پایان: {formatJalali(chosen.ends_at)} · سیاست {chosen.policy_version}</p>}
 <label className="block">شناسهٔ دوره در فایل<input className="input w-full" value={ref} onChange={e=>{setRef(e.target.value);setPreview(null);}}/></label>
 <label className="block">فایل CSV<input className="input w-full" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(file){setCsv(await file.text());setPreview(null);}}}/></label>
 <label className="block">شاهد ثبت‌نام و دلیل ورود<textarea className="input w-full" value={reason} onChange={e=>setReason(e.target.value)} minLength={10}/></label>
 <button className="btn btn-secondary" disabled={busy||!csv||!cohort||reason.trim().length<10} onClick={async()=>{const b=await send("/api/admin/registration-imports/preview",{csv,cohortId:cohort,cohortRef:ref,evidence:reason});if(b)setPreview({...b.data,rows:b.rows});}}>اعتبارسنجی و پیش‌نمایش</button>
 {preview&&<div className="space-y-3"><p>{toPersianDigits(preview.total)} ردیف؛ تأیید فایل مجوز ایجاد نمی‌کند. صاحب حساب باید هویت را اثبات کند.</p><ul>{preview.rows.map(r=><li key={r.externalId}>{r.externalId} · {r.contact} · {r.status}</li>)}</ul><button className="btn btn-primary" disabled={busy} onClick={async()=>{const b=await send(`/api/admin/registration-imports/${preview.importId}/commit`,{hash:preview.hash});if(b)setPreview(null);}}>تأیید همین پیش‌نمایش</button></div>}
 </section>
 <section className="card p-5 space-y-3"><h2 className="font-bold">مجوز دستی با ثبت دلیل</h2><label className="block">حساب<select className="input w-full" value={target} onChange={e=>setTarget(e.target.value)}><option value="">انتخاب حساب</option>{data?.members.map(m=><option key={m.userId} value={m.userId}>{m.label}</option>)}</select></label><p>دوره و دلیل از بخش بالا انتخاب می‌شوند. بازهٔ اصلی همان دوره اعمال می‌شود.</p>
 <button className="btn btn-primary" disabled={busy||!target||!chosen||reason.trim().length<10} onClick={()=>chosen&&void send("/api/admin/cohort-access/commands",{action:"grant",userId:target,cohortId:cohort,moduleKeys:["webinar","resources"],startsAt:chosen.starts_at,endsAtExclusive:chosen.ends_at,reason,idempotencyKey:crypto.randomUUID()})}>اعطای وبینار و منابع</button>
 <button className="btn btn-secondary ms-3" disabled={busy||!chosen||reason.trim().length<10} onClick={()=>void send("/api/admin/course-operations",{action:"cancel-cohort",cohortId:cohort,reason})}>لغو کل دوره با همین دلیل</button>
 </section>
 <section className="card p-5"><h2 className="font-bold mb-3">ثبت‌نام‌ها و صف بررسی</h2><div className="overflow-x-auto"><table className="min-w-[680px] w-full text-sm"><thead><tr><th className="p-2 text-start">منبع / ثبت‌نام</th><th>تماس</th><th>وضعیت</th><th>پیگیری</th></tr></thead><tbody>{data?.registrations.map(r=><tr key={r.id} className="border-t"><td className="p-2">{r.source} / {r.externalId}</td><td>{r.contact}</td><td>{r.status}<p>{r.note}</p></td><td><button className="btn btn-secondary" disabled={busy||!target||reason.trim().length<20} onClick={()=>void send("/api/admin/course-operations",{action:"review",registrationRef:r.id,userId:target,reason})}>ثبت بررسی مستقل هویت</button></td></tr>)}</tbody></table></div>{data?.registrations.length===0&&<p>هنوز ثبت‌نامی وارد نشده است.</p>}</section>
 <section className="card p-5 space-y-3"><h2 className="font-bold">گزارش مجوزهای دوره</h2>{data?.grants.map(g=><div className="flex flex-wrap gap-3 items-center" key={g.grantRef}><span>{data.members.find(m=>m.userId===g.userId)?.label} · {data.cohorts.find(c=>c.id===g.cohortId)?.title} · تا {formatJalali(g.endsAtExclusive)} · {g.revokedAt?"لغوشده":"ثبت‌شده"}</span><button className="btn btn-secondary" disabled={busy||!!g.revokedAt||reason.trim().length<10} onClick={()=>void send("/api/admin/cohort-access/commands",{action:"revoke",grantRef:g.grantRef,userId:g.userId,cohortId:g.cohortId,reason,idempotencyKey:crypto.randomUUID()})}>لغو با دلیل</button></div>)}</section>
 </div>;
}
