"use client";
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {normalizeReturnPath} from './returnPath';
export default function PrivateIdentityForm({phone,returnTo}:{phone:string;returnTo:string}){
  const [firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[nationalId,setNationalId]=useState(''),[password,setPassword]=useState('');
  const [baseVersion,setVersion]=useState(0),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{let cancelled=false;fetch('/api/auth/identity',{cache:'no-store'}).then(async response=>{const body=await response.json();if(cancelled)return;if(!response.ok){setError(body.error);return;}if(body.profile){setFirstName(body.profile.firstName);setLastName(body.profile.lastName);setNationalId(body.profile.nationalId);setVersion(body.version);}setLoaded(true);}).catch(()=>{if(!cancelled)setError('پروفایل بارگذاری نشد. صفحه را دوباره باز کنید.');});return ()=>{cancelled=true;};},[]);
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/auth/identity',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({firstName,lastName,nationalId,baseVersion,consent:consent?'identity-v1':null})});const body=await response.json();if(!response.ok){setError(body.error);return;}setVersion(body.version);setNotice('نسخهٔ جدید پروفایل ذخیره شد. استعلام رسمی هویت هنوز در انتظار است.');}catch{setError('ارتباط برقرار نشد. اطلاعات واردشده حفظ شده است.');}finally{setBusy(false);}}
  async function setOptionalPassword(){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/auth/mobile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'set-password',phone,password})});const body=await response.json();if(!response.ok){setError(body.error);return;}setPassword('');setNotice('رمز اختیاری ذخیره شد. ورود با کد پیامکی همچنان در دسترس است.');}catch{setError('ذخیرهٔ رمز انجام نشد. دوباره تلاش کنید.');}finally{setBusy(false);}}
  return <section className="card-elevated p-6 sm:p-8"><h1 className="text-2xl font-bold mb-4">پروفایل خصوصی من</h1><p className="leading-8 mb-5">شماره همراه تأیید شده است. تطبیق شماره با کد ملی و تأیید رسمی هویت: در انتظار بررسی. اطلاعات زیر در نمای اعضای گروه، تلگرام و گزارش عمومی نمایش داده نمی‌شود.</p>
    <form onSubmit={save} className="space-y-5">
      <div><label className="block mb-2 font-bold" htmlFor="identity-first">نام</label><input id="identity-first" className="input text-base" autoComplete="given-name" value={firstName} onChange={e=>setFirstName(e.target.value)} disabled={busy||!loaded} maxLength={80} required/></div>
      <div><label className="block mb-2 font-bold" htmlFor="identity-last">نام خانوادگی</label><input id="identity-last" className="input text-base" autoComplete="family-name" value={lastName} onChange={e=>setLastName(e.target.value)} disabled={busy||!loaded} maxLength={100} required/></div>
      <div><label className="block mb-2 font-bold" htmlFor="identity-national">کد ملی</label><input id="identity-national" className="input text-base" dir="ltr" inputMode="numeric" autoComplete="off" value={nationalId} onChange={e=>setNationalId(e.target.value)} disabled={busy||!loaded} maxLength={10} required/><p className="text-sm mt-2 leading-7">صفرهای ابتدای کد حفظ می‌شوند. بررسی ساختار کد، تأیید واقعی هویت نیست.</p></div>
      <label className="flex items-start gap-3 leading-8"><input type="checkbox" className="mt-2 h-5 w-5" checked={consent} onChange={e=>setConsent(e.target.checked)} required disabled={busy||!loaded}/>با نگهداری رمزگذاری‌شدهٔ این اطلاعات برای پروفایل خدمت موافقم. استعلام رسمی هنوز فعال نشده است.</label>
      <button className="btn btn-gold w-full" disabled={busy||!loaded}>{busy?'در حال ذخیره…':'ذخیرهٔ نسخهٔ پروفایل'}</button>
    </form>
    <p role="alert" className="mt-4 leading-7" style={{color:'var(--danger)'}}>{error}</p><p role="status" className="mt-4 leading-7">{notice}</p>
    <details className="mt-6"><summary className="cursor-pointer py-3 font-bold">تعیین یا بازیابی رمز اختیاری با کد پیامکی تازه</summary><label htmlFor="identity-password" className="block my-3">رمز جدید، حداقل ۱۲ نویسه</label><input id="identity-password" className="input text-base" type="password" autoComplete="new-password" dir="ltr" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><button type="button" className="btn btn-outline mt-3" disabled={busy||password.length<12} onClick={()=>void setOptionalPassword()}>ذخیرهٔ رمز اختیاری</button></details>
    {baseVersion>0 && <Link className="btn btn-outline w-full mt-6" href={normalizeReturnPath(returnTo)}>ادامه به صفحهٔ درخواستی</Link>}
  </section>;
}
