import {createClient} from '@supabase/supabase-js';import {readFileSync,writeFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {normalisePosition,normaliseDebt} from '../../../../lib/portfolio/financialInput';
const root='docs/ops/seasonal-program/followup-06-feed-market-evidence/',p='C:/Users/Asus/.codex/private/followup06-feed-market/';const s=JSON.parse(readFileSync(p+'secrets.json','utf8')),accounts=JSON.parse(readFileSync(p+'reviewer-credentials.json','utf8')),f=JSON.parse(readFileSync(root+'fixtures.json','utf8'));
const rows=[];
for(const role of ['A','B']){
 const db=createClient(s.origin+'/supabase',s.anon,{auth:{persistSession:false,autoRefreshToken:false}}),r=await db.auth.signInWithPassword({email:accounts[role].email,password:accounts[role].password});if(r.error)throw Error('Native fixture login failed');
 const rpc=async(name:string,args:Record<string,unknown>)=>{const out=await db.rpc(name,args);if(out.error)throw Error('Own synthetic fixture '+name+' '+out.error.code);return out.data;};
 const position={position_key:randomUUID(),manual_label:'دارایی ساختگی ترکیب مستقل '+role,asset_class:'cash',qty:1,unit:'تومان',as_of:'2026-10-01',title:'مالکیت '+role,valuation_mode:'declared',declared_value:1000000,currency:'IRT',valuation_source:'اظهار ساختگی',valuation_as_of:'2026-10-01',valuation_status:'estimated'};
 const prior=await db.from('member_holding_versions').select('id,version').order('version',{ascending:true});if(prior.error)throw Error('Inspect owned ledger before resuming fixture');if(![0,2].includes(prior.data.length))throw Error('Unexpected owned fixture state; no overwrite');
 const first=prior.data.length?prior.data[0]:await rpc('record_member_holdings',{p_positions:[normalisePosition(position)],p_note:'نسخه نخست ساختگی',p_client_token:randomUUID(),p_base_version:0});const second=prior.data.length?prior.data[1]:await rpc('record_member_holdings',{p_positions:[normalisePosition({...position,declared_value:1200000})],p_note:'نسخه دوم ساختگی',p_client_token:randomUUID(),p_base_version:1});
 const debt=await rpc('record_member_debts',{p_debts:[normaliseDebt({debt_key:randomUUID(),title:'بدهی ساختگی '+role,kind:'loan',balance:200000,currency:'IRT',balance_as_of:'2026-10-01'})],p_base_version:2,p_client_token:randomUUID()});
 const needs=await rpc('seasonal_save_needs',{p_cohort:f.cohorts[role],p_base:0,p_body:{experience:'new',interests:['مدیریت دارایی'],goal:'هدف ساختگی مستقل '+role,question:'پرسش ساختگی برای حفظ نیازسنجی'},p_submit:true});
 rows.push({role,userId:accounts[role].id,holdingVersions:[first,second],debt,needs,marker:position.manual_label});
}
writeFileSync(root+'personal-fixtures.json',JSON.stringify({environment:'followup06-feed-market-native-local',createdAt:new Date().toISOString(),source:'Native GoTrue fixture-only login then canonical RPC; independent acceptance must login throughUI',rows},null,2)+'\n');console.log('Own A/B personal assets/debts/needs versioned through native RPC');
