import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parsePublication, publicationCommand, canReadPublication, type PublicationRow } from './publication';
const W='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',C='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const draft={workbookVersionId:W,contentKind:'brief',title:'عنوان',summary:'خلاصه',content:'متن مخاطب',sources:[{url:'https://example.invalid/source',asOf:'2026-09-30',privateNote:'PRIVATE'}],audience:'public',cohortIds:[],channels:['site'],privateNote:'PRIVATE',createdBy:'forged'};
test('publication rebuilds allowlist, preserving sources but no private notes or forged author',()=>{const p=parsePublication(draft);assert.equal(JSON.stringify(p).includes('PRIVATE'),false);assert.equal('createdBy' in p,false);assert.equal(p.sources[0].asOf,'2026-09-30');});
test('audience, exact cohort scope, channel and real date boundaries reject contradictory input',()=>{for(const change of [{audience:'cohort'},{cohortIds:[C]},{channels:['telegram']},{channels:['site','email']},{sources:[{url:'https://user:pass@example.invalid',asOf:'2026-09-30'}]},{sources:[{url:'https://example.invalid',asOf:'2026-02-30'}]}])assert.throws(()=>parsePublication({...draft,...change}));});
test('ready and publish require separate privacy confirmation and reason; withdraw remains possible',()=>{for(const action of ['ready','publish'])assert.throws(()=>publicationCommand({action,versionId:W,idempotencyKey:C,reason:'بازبینی انجام شد',privacyConfirmed:false}));assert.equal(publicationCommand({action:'withdraw',versionId:W,idempotencyKey:C,reason:'خطای منبع یافت شد'}).rpc,'command_research_publication');});
test('direct access denies unapproved, expired grants, other cohorts, draft and withdrawn versions',()=>{const row={...parsePublication({...draft,audience:'cohort',cohortIds:[C]}),id:W,publicationId:W,version:1,createdAt:'2026-09-30',state:'published',approvalCurrent:true} as PublicationRow;assert.equal(canReadPublication(row,[C]),true);assert.equal(canReadPublication(row,[]),false);assert.equal(canReadPublication(row,[W]),false);for(const state of ['draft','ready','withdrawn','approval_invalid'] as const)assert.equal(canReadPublication({...row,state},[C]),false);assert.equal(canReadPublication({...row,approvalCurrent:false},[C]),false);});
