'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {publicationApi} from './PublicationWorkbench';
import {formatTehranDate} from '@/lib/consultation/time';
interface Lead{id:string;name:string;phone:string|null;topic:string|null;message:string|null;status:string;notes:string|null;preferred_date:string|null;preferred_time:string|null;created_at:string;updated_at:string}
const states:Record<string,string>={new:'درخواست تازه',contacted:'تماس و پیگیری',converted:'به خدمت تبدیل‌شده',archived:'بایگانی'};
const style={color:'var(--text)',background:'var(--surface)',borderColor:'var(--line)'};
export default function ServiceRequests(){
 const [rows,setRows]=useState<Lead[]|null>(null),[message,setMessage]=useState(''),[selected,setSelected]=useState<Lead|null>(null),[status,setStatus]=useState('new'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await publicationApi('/api/admin/intelligence/requests');if(r.status!==200)throw Error('درخواست‌ها قابل دریافت نیستند؛ نبود اطلاعات را صفر فرض نمی‌کنیم.');setRows(r.body.items as Lead[]);}catch(e){setMessage(String(e instanceof Error?e.message:e));}}
 useEffect(()=>{void load();},[]);
 async function save(){if(!selected)return;setBusy(true);try{const r=await publicationApi('/api/admin/intelligence/requests',{method:'PATCH',body:JSON.stringify({id:selected.id,updatedAt:selected.updated_at,status,notes})});if(r.status!==200)throw Error(String(r.body.error));await load();setSelected(null);setMessage('پیگیری ثبت شد. درخواست وقت به معنی رزرو تأییدشده نیست.');}catch(e){setMessage(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 return <section className="mx-auto max-w-5xl space-y-5" style={{color:'var(--text)'}}><h1 className="font-display text-2xl font-bold">درخواست مشاوره و پیگیری</h1><p className="leading-8">این فهرست درخواست وقت است. تبدیل‌شدن به خدمت، رابطه مشاور، رضایت پرونده یا رزرو قطعی را خودکار ایجاد نمی‌کند.</p><nav className="flex gap-4"><Link href="/admin/desk" className="min-h-11 underline">میز روزانه</Link><Link href="/dashboard/consultation" className="min-h-11 underline">پرونده‌های مرتبط و موعدها</Link></nav><p role="status" className="leading-7">{message}</p>{rows===null?<button className="btn btn-secondary min-h-11" onClick={()=>void load()}>دریافت دوباره درخواست‌ها</button>:rows.length===0?<p className="card p-5">هنوز درخواستی در فهرست ثبت نشده است.</p>:<div className="overflow-x-auto rounded-xl border" style={style}><table className="w-full text-sm text-start"><caption className="p-3 text-start">آخرین صد درخواست؛ داده خصوصی فقط برای مدیریت پیگیری</caption><thead><tr>{['درخواست‌کننده','موضوع و زمان پیشنهادی','وضعیت','اقدام'].map(x=><th key={x} className="p-3 text-start">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t" style={{borderColor:'var(--line)'}}><td className="p-3 min-w-40"><p>{r.name}</p><p className="text-xs">{formatTehranDate(r.created_at)}</p></td><td className="p-3 min-w-48"><p>{r.topic??'موضوع تکمیل نشده'}</p><p className="text-xs">{r.preferred_date??'روز پیشنهادی تعیین نشده'} · {r.preferred_time??'ساعت پیشنهادی تعیین نشده'}</p></td><td className="p-3">{states[r.status]??'وضعیت نامشخص'}</td><td className="p-3"><button className="btn btn-secondary min-h-11 whitespace-nowrap" onClick={()=>{setSelected(r);setStatus(r.status);setNotes(r.notes??'');}}>ثبت پیگیری</button></td></tr>)}</tbody></table></div>}{selected&&<section className="card p-5 space-y-4"><h2 className="font-bold">پیگیری درخواست {selected.name}</h2><p className="whitespace-pre-wrap leading-7">{selected.message??'شرح درخواست تکمیل نشده است.'}</p><p>راه تماس ثبت‌شده: <span dir="ltr">{selected.phone??'راه تماس ناقص است'}</span></p><label className="block space-y-2">وضعیت<select className="min-h-11 w-full border rounded-lg p-2" style={style} value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(states).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="block space-y-2">یادداشت پیگیری<textarea className="w-full border rounded-lg p-3" style={style} rows={4} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="btn btn-primary min-h-11" disabled={busy||notes.trim().length<5} onClick={()=>void save()}>ذخیره پیگیری</button></section>}</section>;
}
