import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {runInNewContext} from 'node:vm';
import ts from 'typescript';import {AuthSessionMissingError,AuthApiError,AuthRetryableFetchError} from '@supabase/supabase-js';
const require=createRequire(import.meta.url);
const compile=(file,imports)=>{const loaded={exports:{}};runInNewContext(ts.transpileModule(readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:loaded.exports,require:name=>name in imports?imports[name]:require(name),process:{env:{}},AbortSignal,Request,Object,String,Number});return loaded.exports};
const helperFile=new URL('../../lib/auth/session-error.ts',import.meta.url);
const helper=existsSync(helperFile)?compile('../../lib/auth/session-error.ts',{}):{};
function handlers(error,user=null){let reads=0,writes=0;const db={auth:{getUser:async()=>({data:{user},error})},rpc:()=>{reads++;throw Error('must not read private profile')},from:()=>{reads++;throw Error('must not read role')}};const imports={'@/lib/supabase/server':{createClient:async()=>db},'@/lib/supabase/admin':{createAdminClient:()=>{writes++;throw Error('must not create privileged writer')}},'@/lib/auth/mobile-server':{mobileEnabled:()=>true,sameOrigin:()=>true},'@/lib/auth/mobile':{nationalIdFormatValid:()=>true},'@/lib/auth/identity-crypto':{encryptIdentity:()=>{throw Error('must not encrypt')},decryptIdentity:()=>{throw Error('must not decrypt')}},'@/lib/format':{toLatinDigits:x=>x},'@/lib/auth/session-error':helper};return {identity:compile('../../app/api/auth/identity/route.ts',imports),status:compile('../../app/api/auth/status/route.ts',imports),calls:()=>({reads,writes})}}
for(const error of [new AuthRetryableFetchError('PRIVATE upstream transport',503),new AuthApiError('PRIVATE provider detail',503),Error('PRIVATE configuration')]){
 test('actual identity/status HTTP handlers distinguish Auth service failure: '+error.name,async()=>{const h=handlers(error);for(const r of [await h.identity.GET(),await h.identity.POST(new Request('http://localhost/api/auth/identity',{method:'POST',body:'{}'})),await h.status.GET()]){assert.equal(r.status,503);assert.match(r.headers.get('cache-control'),/no-store/);assert.doesNotMatch(await r.text(),/PRIVATE|provider detail/);}assert.deepEqual(h.calls(),{reads:0,writes:0})});
}
for(const error of [null,new AuthSessionMissingError(),new AuthApiError('Session rejected',401),new AuthApiError('Invalid session',403)]){
 test('missing/rejected sessions retain identity401 and status anonymous200: '+(error?.name??'empty'),async()=>{const h=handlers(error);assert.equal((await h.identity.GET()).status,401);assert.equal((await h.identity.POST(new Request('http://localhost/api/auth/identity',{method:'POST',body:'{}'}))).status,401);const r=await h.status.GET();assert.equal(r.status,200);assert.deepEqual(await r.json(),{authenticated:false,role:null});assert.deepEqual(h.calls(),{reads:0,writes:0})});
}
test('email-only real account requires native confirmed phone before identity write',async()=>{const h=handlers(null,{id:'synthetic',phone_confirmed_at:null});assert.equal((await h.identity.POST(new Request('http://localhost/api/auth/identity',{method:'POST',body:'{}'}))).status,401);assert.deepEqual(h.calls(),{reads:0,writes:0})});
